# ----------------------------------------------------------------------
# JCasC Configuration File
# ----------------------------------------------------------------------

## 🎨 Appearance Configuration (dark-theme)
appearance:
  consoleUrlProvider: { }
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
    theme: "dark"

## ⏱️ Timestamper Configuration
unclassified:
  timestamper:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"

tool:
  allure:
    installations:
      - name: "AllureFromMavenCentral"
        properties:
          - installSource:
              installers:
                - allureCommandlineInstaller:
                    id: "2.43.0"
  allure3:
    installations:
      - name: "Allure 3"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

## 🛠️ Job Configuration (configuration-as-code-groovy-plugin)
jobs:
    - script: |
          pipelineJob('example-pipeline-job') {
            definition {
              cps {
                script(new File('/var/jenkins_home/casc_configs/Jenkinsfile').text)
              }
            }
          }