networks:
  beerInfo:
    driver: bridge

services:
  app:
    networks:
      - beerInfo
    image: eclipse-temurin:25-alpine
    container_name: beerInfo-app
    command: java --enable-preview -jar /app/app.jar
    stdin_open: true   # Keep stdin open for input
    tty: true          # Allocate a pseudo-TTY for interaction
    ports:
      - "8080:8080"
    volumes:
      - ./target/beerinfo-1.0.jar:/app/app.jar
    depends_on:
      db:
        condition: service_healthy

  db:
    networks:
      - beerInfo
    image: postgres:latest
    container_name: beerInfo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - ./src/main/resources/sqlscripts/Beers.sql:/docker-entrypoint-initdb.d/Beers.sql
      - ./src/main/resources/sqlscripts/Breweries.sql:/docker-entrypoint-initdb.d/Breweries.sql
      - beerinfo_db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  jenkins:
    networks:
      - beerInfo
    build:
      context: .  # Use the current directory as the build context (Возможно нужно убрать одну точку)
      dockerfile: docker/jenkins/Dockerfile-Jenkins  # Use the Dockerfile.Jenkins in the current directory
    container_name: beerInfo-jenkins
    user: root
    ports:
      - "8888:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # gives access to host Docker daemon
      - ./src:/var/jenkins_home/workspace/example-pipeline-job/src # mount tests inside jenkins for pipeline
      - ./pom.xml:/var/jenkins_home/workspace/example-pipeline-job/pom.xml # mount pom inside jenkins for pipeline
    environment:
      - JENKINS_OPTS=--prefix=/
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins-config.yaml
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://jenkins:8080/login" ]
      interval: 5s
      timeout: 15s
      retries: 2
      start_period: 2s
volumes:
  jenkins_home:
  beerinfo_db_data: