CREATE TABLE Breweries (brewery_id BIGSERIAL PRIMARY KEY, name VARCHAR(40), city VARCHAR(20), state VARCHAR(20), country VARCHAR(30));
INSERT INTO Breweries (name, city, state, country) VALUES ('NorthGate  Brewing ','Minneapolis',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Against the Grain Brewery','Louisville',' KY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Jacks Abby Craft Lagers','Framingham',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mike Hess  Brewing Company','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fort Point Beer Company','San Francisco',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('COAST  Brewing Company','Charleston',' SC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Great Divide  Brewing Company','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tapistry  Brewing','Bridgman',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Lake  Brewing','Holland',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Mitten  Brewing Company','Grand Rapids',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Brewery Vivant','Grand Rapids',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Petoskey  Brewing','Petoskey',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blackrocks Brewery','Marquette',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Perrin  Brewing Company','Comstock Park',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Witchs Hat  Brewing Company','South Lyon',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Founders  Brewing Company','Grand Rapids',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Flat 12 Bierwerks','Indianapolis',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tin Man  Brewing Company','Evansville',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Black Acre  Brewing Co.','Indianapolis',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Breweries Link  Brewing','Plainfield',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bare Hands Brewery','Granger',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Three Pints  Brewing','Martinsville',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Four Fathers  Brewing ','Valparaiso',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Indiana City  Brewing','Indianapolis',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Burn Em  Brewing','Michigan City',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sun King  Brewing Company','Indianapolis',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Evil Czech Brewery','Mishawaka',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('450 North  Brewing Company','Columbus',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Taxman  Brewing Company','Bargersville',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cedar Creek Brewery','Seven Points',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('SanTan  Brewing Company','Chandler',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Boulevard  Brewing Company','Kansas City',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('James Page  Brewing Company','Stevens Point',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Dudes  Brewing Company','Torrance',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ballast Point  Brewing Company','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Anchor  Brewing Company','San Francisco',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Figueroa Mountain  Brewing Company','Buellton',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Avery  Brewing Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Twisted X  Brewing Company','Dripping Springs',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Gonzos BiggDogg  Brewing','Kalamazoo',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Muddy  Brewing','Murphysboro',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lost Nation  Brewing','East Fairfield',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Rising Tide  Brewing Company','Portland',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Rivertowne  Brewing Company','Export',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Revolution  Brewing Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tallgrass  Brewing Company','Manhattan',' KS','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sixpoint Craft Ales','Brooklyn',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('White Birch  Brewing','Hooksett',' NH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Firestone Walker  Brewing Company','Paso Robles',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('SweetWater  Brewing Company','Atlanta',' GA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Flying Mouse Brewery','Troutville',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Upslope  Brewing Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pipeworks  Brewing Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bent Breweriesstillery','Roseville',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Flesk  Brewing Company','Lombard',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pollyanna  Brewing Company','Lemont',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('BuckleDown  Brewing','Lyons',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Destihl Brewery','Bloomington',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Summit  Brewing Company','St. Paul',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Latitude 42  Brewing Company','Portage',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('4 Hands  Brewing Company','Saint Louis',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Surly  Brewing Company','Brooklyn Center',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Against The Grain Brewery','Louisville',' KY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Crazy Mountain  Brewing Company','Edwards',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('SlapShot  Brewing Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mikerphone  Brewing','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Freetail  Brewing Company','San Antonio',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('3 Daughters  Brewing','St Petersburg',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Red Shedman Farm Brewery and Hop...','Mt. Airy',' MD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Appalachian Mountain Brewery','Boone',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Birdsong  Brewing Company','Charlotte',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Union Craft  Brewing','Baltimore',' MD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Atwater Brewery','Detroit',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ale Asylum','Madison',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Two Brothers  Brewing Company','Warrenville',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bent Paddle  Brewing Company','Duluth',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bells Brewery','Kalamazoo',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blue Owl  Brewing','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Speakasy Ales & Lagers','San Francisco',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Black Tooth  Brewing Company','Sheridan',' WY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hopworks Urban Brewery','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Epic  Brewing','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('New Belgium  Brewing Company','Fort Collins',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sierra Nevada  Brewing Company','Chico',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Keweenaw  Brewing Company','Houghton',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Brewery Terra Firma','Traverse City',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Grey Sail  Brewing Company','Westerly',' RI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Kirkwood Station  Brewing Company','Kirkwood',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Goose Island  Brewing Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Broad Brook  Brewing LLC','East Windsor',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Lion Brewery','Wilkes-Barre',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Madtree  Brewing Company','Cincinnati',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Jackie Os Pub & Brewery','Athens',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Rhinegeist Brewery','Cincinnati',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Warped Wing  Brewing Company','Dayton',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blackrocks Brewery','Marquette',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Catawba Valley  Brewing Company','Morganton',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tröegs  Brewing Company','Hershey',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mission Brewery','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Christian Moerlein  Brewing Company','Cincinnati',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('West Sixth  Brewing','Lexington',' KY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Coastal Extreme  Brewing Company','Newport',' RI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('King Street  Brewing Company','Anchorage',' AK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Beer Works Brewery','Lowell',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lone Tree  Brewing Company','Lone Tree',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Four String  Brewing Company','Columbus',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Glabrous  Brewing Company','Pineland',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bonfire  Brewing Company','Eagle',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Thomas Hooker  Brewing Company','Bloomfield',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Woodstock Inn Brewery','North Woodstock','NH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Renegade  Brewing Company','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mother Earth Breweries Company','Vista',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Black Market  Brewing Company','Temecula',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Vault  Brewing Company','Yardley',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Jailbreak  Brewing Company','Laurel',' MD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Smartmouth  Brewing Company','Norfolk',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Base Camp  Brewing Co.','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Alameda  Brewing','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Southern Star  Brewing Company','Conroe',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Steamworks  Brewing Company','Durango',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Horny Goat Breweries Pub','Milwaukee',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cheboygan  Brewing Company','Cheboygan',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Center of the Universe  Brewing C...','Ashland',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ipswich Ale Brewery','Ipswich',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Griffin Claw  Brewing Company','Birmingham',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Karbach  Brewing Company','Houston',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Uncle Billys Brewery and Smokeh...','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Deep Ellum  Brewing Company','Dallas',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Real Ale  Brewing Company','Blanco',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Straub Brewery','St Marys',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Shebeen  Brewing Company','Wolcott',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Stevens Point Brewery','Stevens Point',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Weston  Brewing Company','Weston',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Southern Prohibition  Brewing Com...','Hattiesburg',' MS','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Minhas Craft Brewery','Monroe',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pug Ryans Brewery','Dillon',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hops & Grains  Brewing Company','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sietsema Orchards and Cider Mill','Ada',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Summit  Brewing Company','St Paul',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Core  Brewing & Distilling Company','Springdale',' AR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Independence  Brewing Company','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cigar City  Brewing Company','Tampa',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Third Street Brewerieshouse','Cold Spring',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Narragansett  Brewing Company','Providence',' RI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Grimm Brothers Brewerieshouse','Loveland',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cisco Brewery','Nantucket',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Angry Minnow','Hayward',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Platform Beer Company','Cleveland',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Odyssey Beerwerks','Arvada',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lonerider  Brewing Company','Raleigh',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Oakshire  Brewing','Eugene',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fort Pitt  Brewing Company','Latrobe',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tin Roof  Brewing Company','Baton Rouge',' LA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Three Creeks  Brewing','Sisters',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('2 Towns Ciderhouse','Corvallis',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Caldera  Brewing Company','Ashland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Greenbrier Valley  Brewing Company','Lewisburg',' WV','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Phoenix Ale Brewery','Phoenix',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lumberyard  Brewing Company','Flagstaff',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Uinta  Brewing Company','Salt Lake City',' UT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Four Peaks  Brewing Company','Tempe',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Martin House  Brewing Company','Fort Worth',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Right Brain Brewery','Traverse City',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sly Fox  Brewing Company','Phoenixville',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Round Guys  Brewing','Lansdale',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Great Crescent Brewery','Aurora',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Oskar Blues Brewery','Longmont',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Boxcar  Brewing Company','West Chester',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('High Hops Brewery','Windsor',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Crooked Fence  Brewing Company','Garden City',' ID','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Everybodys  Brewing','White Salmon',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Anderson Valley  Brewing Company','Boonville',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fiddlehead  Brewing Company','Shelburne',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Evil Twin  Brewing','Brooklyn',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('New Orleans Lager & Ale  Brewing ...','New Orleans',' LA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Spiteful  Brewing Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Rahr & Sons  Brewing Company','Fort Worth',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('18th Street Brewery','Gary',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cambridge  Brewing Company','Cambridge',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Carolina Brewery','Pittsboro',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Frog Level  Brewing Company','Waynesville',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wild Wolf  Brewing Company','Nellysford',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('COOP Ale Works','Oklahoma City',' OK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Seventh Son  Brewing Company','Columbus',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Oasis Texas  Brewing Company','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Vander Mill Ciders','Spring Lake',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('St. Julian Winery','Paw Paw',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pedernales  Brewing Company','Fredericksburg',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mothers  Brewing','Springfield',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Modern Monks Brewery','Lincoln',' NE','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Two Beers  Brewing Company','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Snake River  Brewing Company','Jackson',' WY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Capital Brewery','Middleton',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Anthem  Brewing Company','Oklahoma City',' OK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Goodlife  Brewing Co.','Bend',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Breakside Brewery','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Goose Island Brewery Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Burnside  Brewing Co.','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hop Valley  Brewing Company','Springfield',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Worthy  Brewing Company','Bend',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Occidental  Brewing Company','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fearless  Brewing Company','Estacada',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Upland  Brewing Company','Bloomington',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mehana  Brewing Co.','Hilo',' HI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hawaii Nui  Brewing Co.','Hilo',' HI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Peoples  Brewing Company','Lafayette',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fort George Brewery','Astoria',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Branchline  Brewing Company','San Antonio',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Kalona  Brewing Company','Kalona',' IA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Modern Times Beer','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Temperance Beer Company','Evanston',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wisconsin  Brewing Company','Verona',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Crow Peak  Brewing Company','Spearfish',' SD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Grapevine Craft Brewery','Farmers Branch',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Buffalo Bayou  Brewing Company','Houston',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Texian  Brewing Co.','Richmond',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Orpheus  Brewing','Atlanta',' GA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Forgotten Boardwalk','Cherry Hill',' NJ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Laughing Dog  Brewing Company','Ponderay',' ID','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bozeman  Brewing Company','Bozeman',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Choice  Brewing','Broomfield',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Storm  Brewing Company','Odessa',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Carton  Brewing Company','Atlantic Highlands',' NJ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Midnight Sun  Brewing Company','Anchorage',' AK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fat Heads Brewery','Middleburg Heights',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Refuge Brewery','Temecula',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Chatham  Brewing','Chatham',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('DC Brau  Brewing Company','Washington',' DC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Geneva Lake  Brewing Company','Lake Geneva',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Rochester Mills  Brewing Company','Rochester',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cape Ann  Brewing Company','Gloucester',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Borderlands  Brewing Company','Tucson',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('College Street Brewerieshouse and Pub','Lake Havasu City',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Joseph James  Brewing Company','Henderson',' NV','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Harpoon Brewery','Boston',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Back East  Brewing Company','Bloomfield',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Champion  Brewing Company','Charlottesville',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Devils Backbone  Brewing Company','Lexington',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Newburgh  Brewing Company','Newburgh',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wiseacre  Brewing Company','Memphis',' TN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Golden Road  Brewing','Los Angeles',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('New Republic  Brewing Company','College Station',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Infamous  Brewing Company','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Two Henrys  Brewing Company','Plant City',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lift Bridge  Brewing Company','Stillwater',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lucky Town  Brewing Company','Jackson',' MS','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Quest  Brewing Company','Greenville',' SC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Creature Comforts','Athens',' GA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Half Full Brewery','Stamford',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Southampton Publick House','Southampton',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Chapmans  Brewing','Angola',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Barrio  Brewing Company','Tucson',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Santa Cruz Mountain  Brewing','Santa Cruz',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Frankenmuth Brewery','Frankenmuth',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Meckleys Cidery','Somerset Center',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Stillwater Artisanal Ales','Baltimore',' MD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Finchs Beer Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('South Austin Brewery','South Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bauhaus Breweries Labs','Minneapolis',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ozark Beer Company','Rogers',' AR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mountain Town  Brewing Company ','Mount Pleasant',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Otter Creek  Brewing','Waterbury',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Brewery Art','Baltimore',' MD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Denver Beer Company','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ska  Brewing Company','Durango',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tractor  Brewing Company','Albuquerque',' NM','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Peak Organic  Brewing Company','Portland',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cape Cod Beer','Hyannis',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Long Trail  Brewing Company','Bridgewater Corners',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Great Raft  Brewing Company','Shreveport',' LA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Alaskan  Brewing Company','Juneau',' AK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Notch  Brewing Company','Ipswich',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Alchemist','Waterbury',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Three Notchd  Brewing Company','Charlottesville',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Portside Brewery','Cleveland',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Otter Creek  Brewing','Middlebury',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Montauk  Brewing Company','Montauk',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Indeed  Brewing Company','Minneapolis',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Berkshire  Brewing Company','South Deerfield',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Foolproof  Brewing Company','Pawtucket',' RI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Headlands  Brewing Company','Mill Valley',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bolero Snort Brewery','Ridgefield Park',' NJ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Thunderhead  Brewing Company','Kearney',' NE','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Defiance  Brewing Company','Hays',' KS','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Milwaukee  Brewing Company','Milwaukee',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Catawba Island  Brewing','Port Clinton',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Back Forty Beer Company','Gadsden',' AL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Four Corners  Brewing Company','Dallas',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Saint Archer Brewery','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Rogue Ales','Newport',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hales Ales','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tommyknocker Brewery','Idaho Springs',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Baxter  Brewing Company','Lewiston',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Northampton Brewery','Northamtpon',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Black Shirt  Brewing Company','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wachusett  Brewing Company','Westminster',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Widmer Brothers  Brewing Company','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hop Farm  Brewing Company','Pittsburgh',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Liquid Hero Brewery','York',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Matt  Brewing Company','Utica',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Boston Beer Company','Boston',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Old Forge  Brewing Company','Danville',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Utah Brewery Cooperative','Salt Lake City',' UT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Magic Hat  Brewing Company','South Burlington',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blue Hills Brewery','Canton',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Night Shift  Brewing','Everett',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Beach  Brewing Company','Virginia Beach',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Payette  Brewing Company','Garden City',' ID','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Breweries Bus  Brewing','Tampa',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sockeye  Brewing Company','Boise',' ID','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pine Street Brewery','San Francisco',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dirty Bucket  Brewing Company','Woodinville',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Jackalope  Brewing Company','Nashville',' TN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Slanted Rock  Brewing Company','Meridian',' ID','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Piney River  Brewing Company','Bucryus',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cutters  Brewing Company','Avon',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Iron Hill Brewery & Restaurant','Wilmington',' DE','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Marshall Wharf  Brewing Company','Belfast',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Banner Beer Company','Williamsburg',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dicks  Brewing Company','Centralia',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Claremont Craft Ales','Claremont',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Rivertown  Brewing Company','Lockland',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Voodoo Brewery','Meadville',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('D.L. Geary  Brewing Company','Portland',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pisgah  Brewing Company','Black Mountain',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Neshaminy Creek  Brewing Company','Croydon',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Morgan Street Brewery','Saint Louis',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Half Acre Beer Company','Chicago',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Just Beer Project','Burlington',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Bronx Brewery','Bronx',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dead Armadillo Craft  Brewing','Tulsa',' OK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Catawba  Brewing Company','Morganton',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('La Cumbre  Brewing Company','Albuquerque',' NM','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Davids Ale Works','Diamond Springs',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Traveler Beer Company','Burlington',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fargo  Brewing Company','Fargo',' ND','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Sky  Brewing Company','Missoula',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Nebraska  Brewing Company','Papillion',' NE','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Uncle Johns Fruit House Winery','St. Johns',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wormtown Brewery','Worcester',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Due South  Brewing Company','Boynton Beach',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Palisade  Brewing Company','Palisade',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('KelSo Beer Company','Brooklyn',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hardywood Park Craft Brewery','Richmond',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wolf Hills  Brewing Company','Abingdon',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lavery  Brewing Company','Erie',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Manzanita  Brewing Company','Santee',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fullsteam Brewery','Durham',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Four Horsemen  Brewing Company','South Bend',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hinterland Brewery','Green Bay',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Central Coast  Brewing Company','San Luis Obispo',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Westfield River  Brewing Company','Westfield',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Elevator  Brewing Company','Columbus',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Aslan  Brewing Company','Bellingham',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Kulshan Brewery','Bellingham',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pikes Peak  Brewing Company','Monument',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Manayunk  Brewing Company','Philadelphia',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Buckeye  Brewing','Cleveland',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Daredevil  Brewing Company','Shelbyville',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('NoDa  Brewing Company','Charlotte',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Aviator  Brewing Company','Fuquay-Varina',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wild Onion  Brewing Company','Lake Barrington',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hilliards Beer','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mikkeller','Pottstown',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bohemian Brewery','Midvale',' UT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Great River Brewery','Davenport',' IA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mustang  Brewing Company','Mustang',' OK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Airways  Brewing Company','Kent',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('21st Amendment Brewery','San Francisco',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Eddyline Brewery & Restaurant','Buena Vista',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pizza Port  Brewing Company','Carlsbad',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sly Fox  Brewing Company','Pottstown',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Spring House  Brewing Company','Conestoga',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('7venth Sun','Dunedin',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Astoria  Brewing Company','Astoria',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Maui  Brewing Company','Lahaina',' HI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('RoughTail  Brewing Company','Midwest City',' OK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lucette  Brewing Company','Menominee',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bold City Brewery','Jacksonville',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Grey Sail  Brewing of Rhode Island','Westerly',' RI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blue Blood  Brewing Company','Lincoln',' NE','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Swashbuckler  Brewing Company','Manheim',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blue Mountain Brewery','Afton',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Starr Hill Brewery','Crozet',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Westbrook  Brewing Company','Mt. Pleasant',' SC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Shipyard  Brewing Company','Portland',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Revolution  Brewing','Paonia',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Natian Brewery','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Alltechs Lexington  Brewing Company','Lexington',' KY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Oskar Blues Brewery (North Carol...','Brevard',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Orlison  Brewing Company','Airway Heights',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Breckenridge Brewery','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Santa Fe  Brewing Company','Santa Fe',' NM','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Miami  Brewing Company','Miami',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Schilling & Company','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hops & Grain Brewery','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('White Flame  Brewing Company','Hudsonville',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ruhstaller Beer Company','Sacramento',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Saugatuck  Brewing Company','Douglas',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Moab Brewery','Moab',' UT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Macon Beer Company','Macon',' GA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Amnesia  Brewing Company','Washougal',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wolverine State  Brewing Company','Ann Arbor',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Red Tank Cider Company','Bend',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cascadia Ciderworks United','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fate  Brewing Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lazy Monk  Brewing','Eau Claire',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bitter Root  Brewing','Hamilton',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('10 Barrel  Brewing Company','Bend',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tamarack  Brewing Company','Lakeside',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('New England  Brewing Company','Woodbridge',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Seattle Cider Company','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Straight to Ale','Huntsville',' AL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Austin Beerworks','Austin',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blue Mountain Brewery','Arrington',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Coastal Empire Beer Company','Savannah',' GA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Jacks Hard Cider (Hauser Estate...','Biglerville',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Boulder Beer Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Coalition  Brewing Company','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sanitas  Brewing Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Gore Range Brewery','Edwards',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Redstone Meadery','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blue Dog Mead','Eugene',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hess  Brewing Company','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wynkoop  Brewing Company','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ciderboys','Stevens Point',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Armadillo Ale Works','Denton',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Roanoke Railhouse Brewery','Roanoke',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Schlafly  Brewing Company','Saint Louis',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Asher  Brewing Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lost Rhino  Brewing Company','Ashburn',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('North Country  Brewing Company','Slippery Rock',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Seabright Brewery','Santa Cruz',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('French Broad Brewery','Asheville',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Angry Orchard Cider Company','Cincinnati',' OH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Two Roads  Brewing Company','Stratford',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Southern Oregon  Brewing Company','Medford',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Brooklyn Brewery','Brooklyn',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Right Brain Brewery','Traverse City',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Kona  Brewing Company','Kona',' HI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('MillKing It Productions','Royal Oak',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pateros Creek  Brewing Company','Fort Collins',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('OFallon Brewery','OFallon',' MO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Marble Brewery','Albuquerque',' NM','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Wood Brewery','Vadnais Heights',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Howard  Brewing Company','Lenoir',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Downeast Cider House','Leominster',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Swamp Head Brewery','Gainesville',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mavericks Beer Company','Half Moon Bay',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('TailGate Beer','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Northwest  Brewing Company','Pacific',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dad & Dudes Brewerieseria','Aurora',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Centennial Beer Company','Edwards',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Denali  Brewing Company','Talkeetna',' AK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Deschutes Brewery','Bend',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sunken City  Brewing Company','Hardy',' VA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lucette  Brewing Company','Menominie',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Black Tooth  Brewing Company','Sheridan',' WY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Kenai River  Brewing Company','Soldotna',' AK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('River North Brewery','Denver',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Fremont  Brewing Company','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Armstrong  Brewing Company','South San Francisco',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('AC Golden  Brewing Company','Golden',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Bend  Brewing Company','Alpine',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Good Life  Brewing Company','Bend',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Engine 15  Brewing','Jacksonville Beach',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Green Room  Brewing','Jacksonville',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Brindle Dog  Brewing Company','Tampa Bay',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Peace Tree  Brewing Company','Knoxville',' IA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Terrapin  Brewing Company','Athens',' GA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Petes  Brewing Company','San Antonio',' TX','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Okoboji  Brewing Company','Spirit Lake',' IA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Crystal Springs  Brewing Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Engine House 9','Tacoma',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tonka Beer Company','Minnetonka',' MN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Red Hare  Brewing Company','Marietta',' GA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Hangar 24 Craft Brewery','Redlands',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big Elm  Brewing','Sheffield',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Good People  Brewing Company','Birmingham',' AL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Heavy Seas Beer','Halethorpe',' MD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Telluride  Brewing Company','Telluride',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('7 Seas  Brewing Company','Gig Harbor',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Confluence  Brewing Company','Des Moines',' IA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bale Breaker  Brewing Company','Yakima',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('The Manhattan  Brewing Company','New York',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('MacTarnahans  Brewing Company','Portland',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Stillmank Beer Company','Green Bay',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Redhook Brewery','Woodinville',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dock Street Brewery','Philadelphia',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Blue Point  Brewing Company','Patchogue',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Tampa Bay  Brewing Company','Tampa',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Devils Canyon Brewery','Belmont',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Stone Coast  Brewing Company','Portland',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Broken Tooth  Brewing Company','Anchorage',' AK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Seven Brides Brewery','Silverton',' OR','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Newburyport  Brewing Company','Newburyport',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dry Dock  Brewing Company','Aurora',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cans Bar and Canteen','Charlotte',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sprecher  Brewing Company','Glendale',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wildwood  Brewing Company','Stevensville',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('High Noon Saloon And Brewery','Leavenworth',' KS','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Woodchuck Hard Cider','Middlebury',' VT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sea Dog  Brewing Company','Portland',' ME','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Oskar Blues Brewery','Lyons',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Carolina Beer & Beverage','Mooresville',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Krebs  Brewing Company (Petes Pl...','Krebs',' OK','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Warbird  Brewing Company','Fort Wayne',' IN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mudshark  Brewing Company','Lake Havasu City',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Spilker Ales','Cortland',' NE','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wingman Brewery','Tacoma',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Kettle House  Brewing Company','Missoula',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sherwood Forest Brewery','Marlborough',' MA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Cottrell  Brewing','Pawcatuck',' CT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Arctic Craft Brewery','Colorado Springs',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Monkey Paw Pub & Brewery','San Diego',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Crabtree  Brewing Company','Greeley',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Emerald City Beer Company','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Butchers  Brewing','Carlsbad',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('New South  Brewing Company','Myrtle Beach',' SC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Big River  Brewing Company','Chattanooga',' TN','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Twisted Pine  Brewing Company','Boulder',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Flying Dog Brewery','Frederick',' MD','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Uncommon Brewery','Santa Cruz',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Aspen  Brewing Company','Aspen',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Triangle  Brewing Company','Durham',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Bomb Beer Company','New York',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Churchkey Can Company','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Intuition Ale Works','Jacksonville',' FL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Asheville  Brewing Company','Asheville',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Northwoods Brewery','Eau Claire',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Buckbean  Brewing Company','Reno',' NV','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dolores River Brewery','Dolores',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Flat Rock  Brewing Company','Smithton',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Abita  Brewing Company','Abita Springs',' LA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mammoth  Brewing Company','Mammoth Lakes',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Harvest Moon  Brewing Company','Belt',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Grand Canyon  Brewing Company','Williams',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lewis and Clark  Brewing Company','Helena',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Dundee  Brewing Company','Rochester',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Twin Lakes  Brewing Company','Greenville',' DE','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mother Earth  Brewing Company','Kinston',' NC','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Arcadia  Brewing Company','Battle Creek',' MI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Angry Minnow  Brewing Company','Hayward',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Great Northern  Brewing Company','Whitefish',' MT','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Pyramid Breweries','Seattle',' WA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Lancaster  Brewing Company','Lancaster',' PA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Upstate  Brewing Company','Elmira',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Moat Mountain Smoke House & Breweries','North Conway',' NH','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Prescott  Brewing Company','Prescott',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mogollon  Brewing Company','Flagstaff',' AZ','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Wind River  Brewing Company','Pinedale',' WY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Silverton Brewery','Silverton',' CO','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Mickey Finns Brewery','Libertyville',' IL','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Covington Brewerieshouse','Covington',' LA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Daves Brewery','Wilson',' WI','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Ukiah  Brewing Company','Ukiah',' CA','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Butternuts Beer and Ale','Garrattsville',' NY','United States of America');
INSERT INTO Breweries (name, city, state, country) VALUES ('Sleeping Lady  Brewing Company','Anchorage',' AK','United States of America');
